version: "2"

services:
    
#    web:
#        build: ./web/.
#        ports: 
#            - "80:80"
#        depends_on:
#            - db
#
#    db:
#        image: mysql
#        ports: 
#            - "3306:3306"
#        environment:
#            MYSQL_ROOT_HOST: %
#            MYSQL_ROOT_PASSWORD: test
#            MYSQL_USER: user
#            MYSQL_PASSWORD: test
#
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        depends_on:
#            - db
#        ports:
#            - 8888:80
#        environment:
#            MYSQL_ROOT_PASSWORD: test
#            MYSQL_USER: user
#            MYSQL_PASSWORD: test
#            
    svc:
        build: ./java-service/.
        container_name: svc         
        environment:
            DB_HOST: db
            DB_USER: user
            DB_PASS: test
            DB_NAME: myDb
#        depends_on:
#            - mqtt
#            - db
#
#    mqtt:
#        image: toke/mosquitto
#        restart: always
#        ports:
#            - "1883:1883"
#            - "9001:9001"
#